// V9 display patch: better fund cards, inline daily NAV chart, manager search.
// Boot safety: create missing DOM ids before calling render(), otherwise the page can fail to open.
(function(){
  try{
    var cards=document.querySelector('.cards');
    if(cards && !document.getElementById('cntHold')){
      var hold=document.createElement('div');
      hold.className='card';
      hold.innerHTML='<div class="label">持有基金</div><div class="big blue" id="cntHold">0只</div><div class="note">本地保存</div>';
      cards.appendChild(hold);
    }
    var ms=document.getElementById('managerSearch');
    if(ms && !document.getElementById('mkw')) ms.id='mkw';
  }catch(e){console.warn('boot safety skipped',e)}
})();
function dcell(d){return d&&d.ok?`<div class="quote ${cls(d.gszzl)}"><b>${fmt(d.gszzl)}</b><div class="mini">净值 ${d.gsz||d.dwjz||'—'}</div></div>`:'<div class="quote"><b>—</b><div class="mini">—</div></div>'}
function v9Status(d){if(d&&d.ok)return `<span class="green">${d.source||'已更新'}${d.note?'｜'+d.note:''}</span>`;if(d)return `<span class="fail">${d.msg||'失败'}</span>`;return '<span class="mini">等待</span>'}
function v9Perf(f){return `<div class="perf"><div><span class="mini">周</span><b class="${cls(f.week)}">${fmt(f.week)}</b></div><div><span class="mini">月</span><b class="${cls(f.month)}">${fmt(f.month)}</b></div><div><span class="mini">半年</span><b class="${cls(f.halfYear)}">${fmt(f.halfYear)}</b></div><div><span class="mini">一年</span><b class="${cls(f.year)}">${fmt(f.year)}</b></div><div><span class="mini">成立</span><b class="${cls(f.since)}">${fmt(f.since)}</b></div></div>`}
table=function(){let box=$('fundCards');if(!box)return;let rows=list();box.innerHTML=rows.map((f,i)=>{let d=DATA[f.code]||{};return `<div class="fund-card"><div class="fund-top"><div><div class="mini"><span class="rank">#${i+1}</span> 热度前景 ${heatScore(f)} ${HOLD.includes(f.code)?'｜持有':''}</div><div class="fund-name">${f.name}</div><div class="mini"><span class="code">${f.code}</span>｜<span class="tag ${tag(f.group)}">${f.group}</span> <span class="tag gray">${f.tag}</span></div></div>${dcell(d)}</div>${v9Perf(f)}<div class="mini">${d.gztime||d.jzrq||'—'}｜${v9Status(d)}</div><div class="actions-cell"><button class="btn" onclick="openChart('${f.code}')">走势图</button><button class="btn2" onclick="toggleHold('${f.code}')">${HOLD.includes(f.code)?'取消持有':'加入持有'}</button><button class="btn2" onclick="delFund('${f.code}')">删除</button><a class="btn2" target="_blank" href="https://fund.eastmoney.com/${f.code}.html">行情</a></div></div>`}).join('')}
const oldQuick=quick;quick=function(){let f=FUNDS.find(x=>x.code===sel)||ranked(FUNDS)[0];if(!f){oldQuick&&oldQuick();return}let d=DATA[f.code]||{};$('quick').innerHTML=`<div class="fund-name">${f.code} ${f.name}</div><p class="note">快速预览，不显示经理分析。</p><div class="row"><span class="tag ${tag(f.group)}">${f.group}</span><span class="tag gray">${f.category}</span><span class="tag hot">${f.tag}</span></div><p>热度/前景分 ${heatScore(f)}/100</p><div class="meter"><i style="width:${heatScore(f)}%"></i></div><h3>今日涨跌幅 · 净值</h3>${dcell(d)}${v9Perf(f)}<button class="btn" onclick="show('table');openChart('${f.code}')">打开走势图</button>`}
function managerRows(){let k=($('mkw')?.value||'').trim().toLowerCase();return ranked(FUNDS.filter(f=>!k||f.code.includes(k)||f.name.toLowerCase().includes(k)||f.manager.toLowerCase().includes(k)||f.tag.toLowerCase().includes(k)||f.category.toLowerCase().includes(k)))}
managers=function(){let box=$('managerList');if(!box)return;let rows=managerRows();box.innerHTML=rows.map((f,i)=>{let d=DATA[f.code]||{};return `<div class="manager-item" onclick="pick('${f.code}')"><div><span class="rank">#${i+1}</span> <b>${f.code}</b> ${f.name}</div><div class="mini">${f.manager}｜${f.managerType}｜今日 ${d.ok?fmt(d.gszzl):'—'}｜热度 ${heatScore(f)}</div></div>`}).join('');let f=FUNDS.find(x=>x.code===sel)||rows[0]||FUNDS[0];if(f)$('mdetail').innerHTML=`<div class="fund-name">${f.code} ${f.name}</div><div class="row"><span class="tag ${tag(f.group)}">${f.group}</span><span class="tag gray">${f.category}</span><span class="tag hot">${f.tag}</span></div><p>热度/前景分 ${heatScore(f)}/100</p><div class="meter"><i style="width:${heatScore(f)}%"></i></div><h3>行业机会</h3><p class="note">${f.industryNote}</p><h3>产品解读</h3><p class="note">${f.fundNote}</p><h3>基金经理实力/眼光</h3><p class="note"><b>${f.manager}</b>｜${f.managerType}｜<span class="stars">${star(f.managerScore)}</span><br>${f.managerNote}</p><h3>观察策略</h3><p class="note">${f.actionNote}</p>`}
function drawV9Chart(code,points){let f=FUNDS.find(x=>x.code===code)||{name:code};if(!points||points.length<2){$('trendPanel').innerHTML=`<div class="trend"><b>${code} ${f.name}</b><p class="note">走势图数据暂时不可用。基金公司通常每天更新一次净值，稍后可点刷新走势。</p><button class="btn2" onclick="closeTrend()">关闭</button></div>`;return}let vals=points.map(p=>p.nav),min=Math.min(...vals),max=Math.max(...vals),pad=(max-min)*.12||.01,w=900,h=330,l=52,r=22,t=24,b=44,iw=w-l-r,ih=h-t-b;let xy=points.map((p,i)=>({x:l+i/(points.length-1)*iw,y:t+(max+pad-p.nav)/(max-min+pad*2)*ih,p})),path=xy.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '),area=path+` L ${xy[xy.length-1].x} ${h-b} L ${l} ${h-b} Z`,last=points[points.length-1],first=points[0],chg=((last.nav/first.nav-1)*100),grid=[0,.25,.5,.75,1].map(v=>`<line x1="${l}" y1="${t+v*ih}" x2="${w-r}" y2="${t+v*ih}" stroke="rgba(255,255,255,.08)"/><text x="10" y="${t+v*ih+4}" fill="#8da2c0" font-size="11">${(max+pad-v*(max-min+pad*2)).toFixed(3)}</text>`).join('');$('trendPanel').innerHTML=`<div class="trend"><div class="trend-head"><div><h2 style="margin:0">${code} ${f.name}</h2><div class="note">每日净值走势图｜${first.date} 至 ${last.date}｜最新净值 ${last.nav.toFixed(4)}｜区间 ${fmt(chg)}</div></div><div class="row"><button class="btn2" onclick="setRange(30)">近1月</button><button class="btn2" onclick="setRange(90)">近3月</button><button class="btn2" onclick="setRange(180)">近半年</button><button class="btn2" onclick="setRange(365)">近1年</button><button class="btn" onclick="openChart('${code}')">刷新走势</button><button class="btn2" onclick="closeTrend()">关闭</button></div></div><div class="chartbox"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#4f8cff" stop-opacity=".42"/><stop offset="1" stop-color="#4f8cff" stop-opacity="0"/></linearGradient></defs>${grid}<path d="${area}" fill="url(#g)"/><path d="${path}" fill="none" stroke="#4f8cff" stroke-width="3"/><circle cx="${xy[xy.length-1].x}" cy="${xy[xy.length-1].y}" r="5" fill="#fff" stroke="#4f8cff" stroke-width="3"/><text x="${l}" y="${h-14}" fill="#8da2c0" font-size="11">${first.date}</text><text x="${w-120}" y="${h-14}" fill="#8da2c0" font-size="11">${last.date}</text></svg></div><p class="note">说明：走势图使用每日公布净值绘制，非盘中实时K线；每天净值更新后可点“刷新走势”。</p></div>`;$('trendPanel').scrollIntoView({behavior:'smooth',block:'start'})}
openChart=async function(code){sel=code;let p=$('trendPanel');if(!p){return}p.innerHTML=`<div class="trend"><b>${code}</b><p class="note">正在加载每日净值走势图……</p></div>`;try{let r=await fetch('/api/history?code='+code+'&size='+chartRange+'&t='+Date.now(),{cache:'no-store'});let j=await r.json();drawV9Chart(code,j.points||[])}catch(e){drawV9Chart(code,[])}}
setRange=function(n){chartRange=n;if(sel)openChart(sel)};function closeTrend(){$('trendPanel').innerHTML=''}
let mk=$('mkw');if(mk)mk.addEventListener('input',render);render();