// portfolio-pro.js - 持仓系统增强：份额、摊薄成本、卖出扣减、浮动/已实现收益、重复持仓检测
(function(){
  const $=id=>document.getElementById(id);
  const T='fundTradesV28',P='fundPositionsV28',A='fundAlertsV29';
  function read(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}}
  function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
  function money(n){return Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2})}
  function pct(n){n=Number(n||0);return (n>=0?'+':'')+n.toFixed(2)+'%'}
  function cls(n){return Number(n||0)>=0?'red':'green'}
  function fund(code){try{return (FUNDS||[]).find(f=>String(f.code)===String(code))||{code,name:'基金 '+code,group:'未分组',risk:'—',tag:'—',category:'—'}}catch(e){return{code,name:'基金 '+code,group:'未分组',risk:'—',tag:'—',category:'—'}}}
  function nav(code){try{const d=DATA[String(code)]||{};return Number(d.gsz||d.dwjz||d.nav||0)}catch(e){return 0}}
  function bucketOf(f){const s=(f.name+' '+f.category+' '+f.group+' '+f.tag).toLowerCase();if(/半导体|芯片|电子|ai|人工智能|通信|5g|算力|cpo|光模块|科技|纳斯达克/.test(s))return '科技成长';if(/白酒|消费|食品|饮料/.test(s))return '消费';if(/医疗|医药|创新药/.test(s))return '医疗';if(/有色|金属|黄金|铜|稀土|锂/.test(s))return '资源周期';if(/电力|电网|公用|绿电/.test(s))return '电力电网';if(/机器人|自动化/.test(s))return '机器人';if(/全球|qdii|海外|中概|恒生|标普/.test(s))return '海外';return '其他'}
  function buildPositions(){
    const trades=read(T);const map={};let realized=0;
    if(trades.length){
      trades.forEach(t=>{const code=String(t.code||'').trim();if(!/^\d{6}$/.test(code))return;const amount=Number(t.amount||0), price=Number(t.nav||0);if(!map[code])map[code]={code,shares:0,costBasis:0,realized:0,notes:[]};const p=map[code];if(t.type==='买入'){if(amount>0&&price>0){const sh=amount/price;p.shares+=sh;p.costBasis+=amount}else if(amount>0){p.costBasis+=amount}p.notes.push(t.note||'买入')}else if(t.type==='卖出'){if(amount>0&&price>0&&p.shares>0){const sellShares=Math.min(amount/price,p.shares);const avg=p.shares?p.costBasis/p.shares:0;const costOut=sellShares*avg;const sellMoney=sellShares*price;const gain=sellMoney-costOut;p.shares-=sellShares;p.costBasis=Math.max(0,p.costBasis-costOut);p.realized+=gain;realized+=gain}else if(amount>0&&p.costBasis>0){const costOut=Math.min(amount,p.costBasis);p.costBasis-=costOut;p.realized+=amount-costOut;realized+=amount-costOut}p.notes.push(t.note||'卖出')}else{p.notes.push(t.note||'观察')}})
    }else{
      read(P).forEach(x=>{const code=String(x.code||'').trim();const amount=Number(x.amount||0),cost=Number(x.cost||0);if(!/^\d{6}$/.test(code)||!amount)return;map[code]={code,shares:cost>0?amount/cost:0,costBasis:amount,realized:0,notes:[x.note||'历史持仓']}})
    }
    const list=Object.values(map).filter(p=>p.shares>0||p.costBasis>0).map(p=>{const f=fund(p.code),n=nav(p.code),avg=p.shares?p.costBasis/p.shares:0,value=n&&p.shares?n*p.shares:p.costBasis,float=n&&p.shares?value-p.costBasis:0,ret=p.costBasis?float/p.costBasis*100:0;return {...p,f,nav:n,avg,value,float,ret,bucket:bucketOf(f)}});
    const totalValue=list.reduce((s,p)=>s+p.value,0);list.forEach(p=>p.weight=totalValue?p.value/totalValue*100:0);return{list,realized,totalValue,totalCost:list.reduce((s,p)=>s+p.costBasis,0),floating:list.reduce((s,p)=>s+p.float,0)}}
  function duplicateHtml(list){const groups={};list.forEach(p=>{if(!groups[p.bucket])groups[p.bucket]=[];groups[p.bucket].push(p)});const total=list.reduce((s,p)=>s+p.value,0)||1;let warns=[];Object.keys(groups).forEach(k=>{const arr=groups[k],v=arr.reduce((s,p)=>s+p.value,0),w=v/total*100;if(arr.length>=3||w>45)warns.push({k,arr,w})});if(!warns.length)return '<div class="portfolio-pro-good">暂无明显重复持仓。当前组合分布相对分散。</div>';return '<div class="duplicate-list">'+warns.map(w=>`<div class="portfolio-pro-alert"><b>${w.k} 占比 ${w.w.toFixed(1)}%，共 ${w.arr.length} 只</b><div class="mini">${w.arr.map(p=>p.code+' '+p.f.name).join(' ｜ ')}</div><p class="note">提示：同方向基金重复度偏高，建议保留 1-2 只核心，其余作为观察或降低仓位。</p></div>`).join('')+'</div>'}
  function allocationHtml(list){const groups={};list.forEach(p=>{groups[p.bucket]=(groups[p.bucket]||0)+p.value});const total=list.reduce((s,p)=>s+p.value,0)||1;return Object.keys(groups).sort((a,b)=>groups[b]-groups[a]).map(k=>{const w=groups[k]/total*100;return `<div class="allocation-row"><b>${k}</b><div class="allocation-bar"><i style="width:${Math.min(100,w)}%"></i></div><span>${w.toFixed(1)}%</span></div>`}).join('')||'<p class="note">暂无持仓分布。</p>'}
  function render(){
    if(!$('portfolioRoot')){return}
    const b=buildPositions(),list=b.list,totalProfit=b.floating+b.realized,totalRet=b.totalCost?totalProfit/b.totalCost*100:0;
    $('portfolioRoot').innerHTML=`<div class="card"><h2>持仓计划 Pro</h2><p class="note">已升级为按买卖记录自动计算份额、摊薄成本、卖出扣减、浮动收益和已实现收益。</p><div class="portfolio-stats"><div class="portfolio-stat"><span class="mini">剩余成本</span><b>¥${money(b.totalCost)}</b></div><div class="portfolio-stat"><span class="mini">当前市值</span><b>¥${money(b.totalValue)}</b></div><div class="portfolio-stat"><span class="mini">浮动盈亏</span><b class="${cls(b.floating)}">¥${money(b.floating)}</b></div><div class="portfolio-stat"><span class="mini">已实现收益</span><b class="${cls(b.realized)}">¥${money(b.realized)}</b></div></div><div class="portfolio-pro-alert"><b>总收益：<span class="${cls(totalProfit)}">¥${money(totalProfit)}｜${pct(totalRet)}</span></b><div class="mini">总收益 = 浮动盈亏 + 已实现收益。卖出记录会自动扣减份额。</div></div><div class="portfolio-grid"><div><h3>记录买卖</h3><div class="portfolio-form"><select id="trType"><option>买入</option><option>卖出</option><option>观察</option></select><input id="trCode" placeholder="基金代码"><input id="trAmount" placeholder="买/卖金额"><input id="trNav" placeholder="成交净值"><input id="trNote" placeholder="备注"><button class="btn" onclick="addTradeUnified()">记录</button></div><p class="note">买入：金额 ÷ 净值 = 份额；卖出：按成交净值自动扣减份额并计算已实现收益。</p><h3>持仓明细</h3>${list.map(p=>`<div class="position-pro-row"><div><b>${p.code} ${p.f.name}</b><div class="mini">${p.bucket}｜${p.f.tag}｜${p.f.risk}</div></div><div>份额 ${money(p.shares)}</div><div>成本 ${p.avg?p.avg.toFixed(4):'—'} / 当前 ${p.nav||'—'}</div><div>市值 ¥${money(p.value)}</div><div class="${cls(p.float)}">${pct(p.ret)}｜¥${money(p.float)}</div><div>${p.weight.toFixed(1)}%</div></div>`).join('')||'<p class="note">暂无持仓。先记录一笔买入。</p>'}</div><div><h3>持仓占比</h3>${allocationHtml(list)}<h3>重复持仓检测</h3>${duplicateHtml(list)}<h3>高波动仓位提醒</h3>${list.filter(p=>/高|很高/.test(p.f.risk)&&p.weight>15).map(p=>`<div class="portfolio-pro-alert"><b>${p.code} ${p.f.name}：${p.weight.toFixed(1)}%</b><div class="mini">风险等级 ${p.f.risk}，仓位偏高，注意回撤。</div></div>`).join('')||'<div class="portfolio-pro-good">暂无高波动基金仓位过高。</div>'}</div></div></div>`}
  window.renderPortfolioUnified=render;
  window.addTradeUnified=function(){const type=$('trType').value,code=$('trCode').value.trim(),amount=Number($('trAmount').value),nv=Number($('trNav').value),note=$('trNote').value.trim();if(!/^\d{6}$/.test(code)||!amount){alert('请输入6位基金代码和金额');return}if((type==='买入'||type==='卖出')&&!nv){alert('买入/卖出需要填写成交净值，才能计算份额和成本');return}const arr=read(T);arr.push({id:String(Date.now()),type,code,amount,nav:nv,note,date:new Date().toLocaleString('zh-CN',{hour12:false})});write(T,arr);render()}
  window.delTradeUnified=function(id){write(T,read(T).filter(x=>x.id!==id));render()}
  function boot(){if(document.querySelector('#portfolio.view.active'))render();const nav=document.querySelector('[data-v="portfolio"]');if(nav&&!nav.__pro){nav.addEventListener('click',()=>setTimeout(render,80));nav.__pro=true}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,1000);
})();